# Generated by Django 3.0.1 on 2019-12-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20191226_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='drinks_type',
        ),
        migrations.AddField(
            model_name='drinks',
            name='calorie',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drinks',
            name='cup',
            field=models.CharField(default='L', max_length=3),
        ),
    ]
