# Generated by Django 3.0.1 on 2019-12-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20191227_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='bubble',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drinks',
            name='cafe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drinks',
            name='hotcold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drinks',
            name='juice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drinks',
            name='milk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drinks',
            name='tea',
            field=models.BooleanField(default=False),
        ),
    ]
